# Generated by Django 3.2.13 on 2023-05-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('original_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_path', models.TextField()),
                ('genre_id', models.IntegerField()),
                ('api_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.keyword')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='movies',
            field=models.ManyToManyField(related_name='keywords', through='movies.MovieKeyword', to='movies.Movie'),
        ),
    ]
