# Generated by Django 3.2.13 on 2023-05-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
