# Generated by Django 3.2.18 on 2023-05-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarloImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('original_title', models.CharField(max_length=255)),
                ('painter', models.CharField(max_length=255)),
                ('img_url', models.ImageField(upload_to='karloResults/')),
            ],
        ),
    ]
