# Generated by Django 3.2.18 on 2023-05-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
